/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useTexture, useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function BuildingModel(props) {
  const groupRef = useRef();
  const scroll = useScroll();
  const { nodes } = useGLTF("/building2.glb");
  const bakedBuildingTexture = useTexture("/buiding_bake.jpg");
  const logoTexture2 = useTexture("/logo.png");
  bakedBuildingTexture.flipY = false; // Important for correct mapping
  logoTexture2.flipY = false;

  useFrame((state, delta) => {
    const offset = scroll.offset;
    state.camera.rotation.set(
      Math.sin(offset) * 2,
      Math.atan(offset * Math.PI * 2) * -4,
      Math.cos(offset * Math.PI) * -10
    );
    groupRef.current.rotation.set(-0.5, offset * 5, 0); // Moves model up/down with scroll
    state.camera.lookAt(0, 0,0);
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tahitha_logo.geometry}
        position={[3.416, 3.593, 0.912]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.688}
      >
        <meshBasicMaterial map={logoTexture2} transparent={true} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.build.geometry}
        material={nodes.build.material}
        position={[3.412, 1.754, 0.811]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.189, 0.189, 0.159]}
      >
        <meshBasicMaterial map={bakedBuildingTexture} transparent={true} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/building2.glb");
