/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useTexture, useGLTF, Center } from "@react-three/drei";

export function Model(props) {
  const { nodes } = useGLTF("/building.glb");
  const bakedTexture = useTexture("/baked2.jpg");
  const logoTexture = useTexture("/logo.png");
  bakedTexture.flipY = false; // Important for correct mapping
  logoTexture.flipY = false;
  console.log(bakedTexture);

  return (
    <group {...props} dispose={null} position={[2.2, -2.6, 0.08]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.logo.geometry}
        position={[-0.61, 2.999, -0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.688}
      >
        <meshBasicMaterial map={logoTexture} transparent={true} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        position={[-0.909, -0.092, 0.242]}
        scale={0.19}
      >
        <meshStandardMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        position={[-0.336, -0.092, 0.242]}
        scale={0.19}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        position={[0.214, -0.092, 0.242]}
        scale={0.19}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        position={[-1.471, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        position={[-1.471, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        position={[-0.355, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        position={[-0.925, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        position={[-0.355, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        position={[0.191, -0.225, 0.004]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        position={[-1.463, 2.223, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.045}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        position={[0.533, -0.225, -0.297]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        position={[0.533, -0.225, -0.843]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        position={[0.533, -0.225, -1.412]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        position={[0.533, -0.225, -1.958]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        position={[0.223, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        position={[0.223, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        position={[-0.323, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        position={[-1.77, -0.225, -1.998]}
        rotation={[Math.PI / 2, 0, 1.571]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        position={[-1.77, -0.225, -1.452]}
        rotation={[Math.PI / 2, 0, 1.571]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        position={[-0.892, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        position={[-1.77, -0.225, -0.882]}
        rotation={[Math.PI / 2, 0, 1.571]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        position={[-1.77, -0.225, -0.336]}
        rotation={[Math.PI / 2, 0, 1.571]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        position={[-0.892, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        position={[-1.438, -0.225, -2.282]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        position={[0.516, 2.223, -0.287]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.045}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        position={[0.239, 2.223, -2.266]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.045}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        position={[-1.74, 2.223, -1.989]}
        rotation={[Math.PI / 2, 0, 1.571]}
        scale={1.045}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={nodes.Object_24.material}
        position={[-1.193, -0.333, 0.035]}
        scale={0.074}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        position={[-0.624, -0.333, 0.035]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        position={[-0.079, -0.333, 0.035]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        position={[0.515, -0.333, 0.035]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        position={[0.564, -0.333, -0.01]}
        rotation={[0, 1.571, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        position={[0.564, -0.333, -0.575]}
        rotation={[0, 1.571, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        position={[0.564, -0.333, -1.143]}
        rotation={[0, 1.571, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        position={[0.564, -0.333, -1.689]}
        rotation={[0, 1.571, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={nodes.Object_80.material}
        position={[0.564, -0.333, -2.282]}
        rotation={[0, 1.571, 0]}
        scale={0.074}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        position={[-1.802, -0.333, -2.284]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        position={[-1.802, -0.333, -1.719]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        position={[-1.802, -0.333, -1.151]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        position={[-1.802, -0.333, -0.605]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        position={[-1.802, -0.333, -0.012]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        position={[0.51, -0.333, -2.313]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        position={[-0.055, -0.333, -2.313]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        position={[-0.623, -0.333, -2.313]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        position={[-1.169, -0.333, -2.313]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        position={[-1.762, -0.333, -2.313]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        position={[0.5, 1.738, -0.022]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        position={[-0.045, 1.738, -0.022]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        position={[-0.614, 1.738, -0.022]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        position={[-1.184, 1.738, -0.022]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        position={[-1.709, 1.738, -0.022]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        position={[0.5, 1.738, -2.239]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        position={[-0.045, 1.738, -2.239]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        position={[-0.614, 1.738, -2.239]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        position={[-1.184, 1.738, -2.239]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        position={[-1.709, 1.738, -2.239]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        position={[0.5, 1.738, -1.701]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        position={[-1.709, 1.738, -1.701]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        position={[0.5, 1.738, -1.134]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        position={[-1.709, 1.738, -1.134]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        position={[0.5, 1.738, -0.565]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        position={[-1.709, 1.738, -0.565]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        position={[-1.758, -0.333, 0.035]}
        scale={0.074}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        position={[-1.099, -0.2, 0.035]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.382}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        position={[0.017, -0.2, 0.035]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.382}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        position={[-1.432, 0.157, 0.032]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        position={[-1.478, 0.633, 0.034]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.639}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        position={[-0.585, 2.012, -0.923]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        position={[-1.787, -0.226, -1.959]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        position={[0.561, 0.157, -0.335]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        position={[0.549, -0.226, -0.335]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        position={[-0.149, -0.2, -2.313]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.382}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        position={[-1.264, -0.2, -2.313]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.382}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        position={[-1.787, 0.157, -1.959]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        position={[0.185, 0.157, -2.31]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.726}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        position={[0.481, 0.633, -0.307]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.639}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        position={[0.07, 0.633, -2.24]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.639}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        position={[-1.889, 0.633, -1.899]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.639}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        position={[-0.585, 2.363, -0.923]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        position={[-0.612, 0.338, -0.923]}
      >
        <meshBasicMaterial map={bakedTexture} />
      </mesh>
      <group
        position={[0, 1.663, -0.181]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.144}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6001.geometry}
            position={[0, -3.483, 4.248]}
            scale={[1.305, 1.305, 1.103]}
          >
            <meshBasicMaterial map={bakedTexture} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8001.geometry}
            position={[0, -3.483, 4.248]}
            scale={[1.305, 1.305, 1.103]}
          >
            <meshBasicMaterial map={bakedTexture} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4001.geometry}
            position={[0, -3.483, 4.248]}
            scale={1.305}
          >
            <meshBasicMaterial map={bakedTexture} />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/building.glb");
